/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    'BaseButton.story': typeof import('./src/components/BaseButton.story.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
  }
}
